### ISSUE TITLE
Need help Unknown field state in domain [["state","in",["cancelled","close"]]]

### ISSUE THREAD

**Issue by 360org** [OCA/project#221]
i have install Project Task Default Stage on v10 but it has error The error is Error: Unknown field state in domain [["state","in",["cancelled","close"]]] when i try to click to seting plz help

**Comment by dreispt** [comment]
Have you tried restarting the server or reinstalling/upgrading the module?
Can you provide the full traceback in the server log?

**Comment by 360org** [comment]
here is there error 
http://w360s.com.vn/web/content/3560-cdfa10d/web.assets_backend.js:1762
Traceback:
Error: Unknown field state in domain [["state","in",["cancelled","close"]]]
    at Object.compute_domain (http://w360s.com.vn/web/content/3560-cdfa10d/web.assets_backend.js:1762:42)
    at Class.compute_domain (http://w360s.com.vn/web/content/3560-cdfa10d/web.assets_backend.js:2181:344)
    at Class.process_modifiers (http://w360s.com.vn/web/content/3560-cdfa10d/web.assets_backend.js:2216:60)
    at Class.trigger (http://w360s.com.vn/web/content/3301-6072695/web.assets_common.js:3098:180)
    at Class.trigger (http://w360s.com.vn/web/content/3301-6072695/web.assets_common.js:3102:148)
    at Class.on_form_changed (http://w360s.com.vn/web/content/3560-cdfa10d/web.assets_backend.js:2133:98)
    at Array.<anonymous> (http://w360s.com.vn/web/content/3560-cdfa10d/web.assets_backend.js:2130:6)
    at Array.<anonymous> (http://w360s.com.vn/web/content/3301-6072695/web.assets_common.js:547:681)
    at fire (http://w360s.com.vn/web/content/3301-6072695/web.assets_common.js:541:299)
    at Object.add [as done] (http://w360s.com.vn/web/content/3301-6072695/web.assets_common.js:542:467)

**Comment by dreispt** [comment]
Hi, we can't do much with the javascript traceback.
Do you see any errors in the server log?

Please share the steps to reproduce the error.
Can you reproduce it in the OCA Runbot?

**Comment by 360org** [comment]
how cai i build oca runbot? where do i get server log? sorry im newbies

**Comment by dreispt** [comment]
Use the "Try me on Runbot" button in the README: 
https://github.com/OCA/project/tree/10.0/project_task_default_stage#configuration

**Comment by 360org** [comment]
i think me same cause 
https://www.odoo.com/forum/help-1/question/issue-in-project-module-unknown-field-state-in-domain-110519 but i dont know how to fixed it

**Comment by dreispt** [comment]
Did you try Runbot? Or can you reproduce in a new locally installed database?

**Comment by simahawk** [comment]
outdated, feel free to reopen if needed
