### ISSUE TITLE
Project Timeline issue

### ISSUE THREAD

**Issue by mareban** [OCA/project#300]
Hello,

We've installed the project_timeline module which install the web_timeline module too !

It works but all the modification are not kept cause of an sql error !!

Is it a bug or a config problem ?

Note that our timezone is "Europe/Brussels".

Thanks for your help.

 bad query: UPDATE "project_task" SET "date_end"='2017-07-19 22:29:09',"project_id"=13,"date_start"='2017-07-19 21:36:00',"write_uid"=6,"write_date"=(now() at time zone 'UTC') WHERE id IN (31)

**Comment by pedrobaeza** [comment]
Please put complete stack trace, steps to reproduce, and try on runbot if you have the same problem.

**Comment by mareban** [comment]
I've update Odoo (last nightly), remove all modules, restart odoo and postgres and still the same problem !

I've checked on runbot and in the tasks form, and 2 fields is missing in our task form :  "from days" and "estimated days" !

Do we have to install all the tasks modules from the project repository please ?

Thx.

**Comment by pedrobaeza** [comment]
You have to try on OCA runbot. Just follow the "Try me on runbot" link inside module README.rst.

**Comment by pedrobaeza** [comment]
And please, exact steps to reproduce the problem.

**Comment by mareban** [comment]
That's what i did :-) and in comparison, in the task form, 2 fields is missing : "from days" and "estimated days" !

I've install all the *task* modules and *stage* and it's the same !

To reproduce the error, if i try to move, reduce or increase something on the gantt, i've got an error message saying that i'm  trying to delete something or a mandatory field is missing !

In the log i have a bad query sql ...

Thx

**Comment by pedrobaeza** [comment]
Sorry, but I doubt you are trying in runbot. The link for accessing it is http://3297423-10-0-b0187d.runbot2.odoo-community.org/web

I have just tried right now and it's working correctly.

**Comment by mareban** [comment]
I'm logged in : http://3297423-10-0-b0187d.runbot2.odoo-community.org/web?debug=1#view_type=timeline&model=project.task&action=246&active_id=6 !

I've installe the module project_recalculate and now the 2 missing fields in our Odoo installation are present !

Now we have another error, maybe a dependancy problem or maybe i have to recreate tasks  ?

Thx

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<string>", line 2, in write
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python2.7/site-packages/odoo/addons/project_recalculate/models/project_task.py", line 255, in write
    vals = self._dates_onchange(vals)

  File "/usr/lib/python2.7/site-packages/odoo/addons/project_recalculate/models/project_task.py", line 67, in _dates_onchange
    default_interval=default_interval, resource_id=resource.id,
  File "/usr/lib/python2.7/site-packages/odoo/addons/project_recalculate/models/resource_calendar.py", line 14, in get_working_days_of_date
    self.ensure_one()
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4826, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: resource.calendar()
