### ISSUE TITLE
[RFC] Module project_closing became obsolete?

### ISSUE THREAD

**Issue by astirpe** [OCA/project#353]
I'm noticing that all the PRs (both 10.0 and 11.0) opened during the last four weeks have the Travis tests failing.

The travis logs say:
```
FAIL: test_analytic_toggle_active (odoo.addons.project_closing.tests.test_project.TestProject)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/project/project_closing/tests/test_project.py", line 40, in test_analytic_toggle_active
`     self.assertFalse(self._analytic1.active)
` AssertionError: True is not false
FAIL: test_project_toggle_active (odoo.addons.project_closing.tests.test_project.TestProject)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/project/project_closing/tests/test_project.py", line 24, in test_project_toggle_active
`     self.assertFalse(self._analytic1.active)
` AssertionError: True is not false
FAILED
```

Indeed four weeks ago there was a commit (https://github.com/odoo/odoo/commit/055f8e0fcdca7c279642c1e35fe0a1ecd84a025c) that causes the tests of `project_closing` failing. That commit sets the analytic account to 'archived' when it's related project is archived.

It seems that the functionality provided by module `project_closing` is the same introduced by commit https://github.com/odoo/odoo/commit/055f8e0fcdca7c279642c1e35fe0a1ecd84a025c. Does that commit obsolete module `project_closing`?

In any case, all the recent Travis tests are failing because of this and all the new PRs are red.

**Comment by elicoidal** [comment]
@astirpe I tend to agree with you

**Comment by simahawk** [comment]
:+1:

**Comment by simahawk** [comment]
so, shall we remove it? :)

**Comment by pedrobaeza** [comment]
Yes, please

**Comment by astirpe** [comment]
Removal proposed in PR #356

**Comment by astirpe** [comment]
Still to be fixed for 10.0

**Comment by pedrobaeza** [comment]
It has been automatically closed on PR merge. I reopen then.

**Comment by mpanarin** [comment]
fix for v10.0
https://github.com/OCA/project/pull/358

**Comment by pedrobaeza** [comment]
There's already #357.

**Comment by Jerther** [comment]
There seems to be some leftovers here: https://github.com/OCA/project/tree/11.0/setup/project_closing

**Comment by simahawk** [comment]
that should be automatically dropped by oca-git-bot, which did not pass by yet.
@sbidoul am I wrong?  In any case that path is harmless.

**Comment by sbidoul** [comment]
@simahawk hm, that bit is still on my todo list.

**Comment by sbidoul** [comment]
https://github.com/acsone/setuptools-odoo/issues/21 (contribs always welcome :smile:)

**Comment by simahawk** [comment]
@sbidoul ah! my memory tricked me then :stuck_out_tongue: Tnx for the link then! :)
