### ISSUE TITLE
Project_parent Odoo 10 error

### ISSUE THREAD

**Issue by mareban** [OCA/project#359]
Hello,

I've created 2 new projects (A and B)  and declared  A as parent project for B, and get this error message :

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4699, in search_read
    result = records.read(fields)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3021, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5214, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 981, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 936, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/site-packages/odoo/addons/bi_project_template/project_template.py", line 60, in count_sequence
    if self.stage_id.id == int(state_new_id):
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 864, in __get__
    record.ensure_one()
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 4826, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: project.project(53, 54)

Did i miss something ??

Thanks for your help.

**Comment by pedrobaeza** [comment]
This error has nothing to do with this repository and more with a custom module called bi_project_template.
