### ISSUE TITLE
Error while installing Project Key on Odoo 11 ce with Demo Data

### ISSUE THREAD

**Issue by wshamasneh** [OCA/project#440]
An error is show up while installing Project Key on Odoo 11 ce with Demo Data.
the error is as the following:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 200, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_key\hooks.py", line 8, in post_init_hook
    env['project.project']._set_default_project_key()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_key\models\project_project.py", line 179, in _set_default_project_key
    ]):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 980, in __set__
    record.write({self.name: write_value})
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_key\models\project_project.py", line 55, in write
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project\models\project.py", line 270, in write
    res = super(Project, self).write(vals) if vals else True
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 282, in write
    result = super(MailThread, self).write(values)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_syncer\models\syncer.py", line 106, in write
    return super(Base, self).write(vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3089, in write
    self._write(old_vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_syncer\models\syncer.py", line 93, in _write
    return super(Base, self)._write(vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3190, in _write
    cr.execute(query, params + (sub_ids,))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "project_project_project_key_unique"
DETAIL:  Key (key)=(IP) already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_syncer\http.py", line 9, in __call__
    result = self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1231, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions.py", line 554, in run
    res = func(action, eval_context=eval_context)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\website\models\ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions.py", line 430, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 200, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_key\hooks.py", line 8, in post_init_hook
    env['project.project']._set_default_project_key()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_key\models\project_project.py", line 179, in _set_default_project_key
    ]):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 980, in __set__
    record.write({self.name: write_value})
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project_key\models\project_project.py", line 55, in write
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\project\models\project.py", line 270, in write
    res = super(Project, self).write(vals) if vals else True
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\mail\models\mail_thread.py", line 282, in write
    result = super(MailThread, self).write(values)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_syncer\models\syncer.py", line 106, in write
    return super(Base, self).write(vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3089, in write
    self._write(old_vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_syncer\models\syncer.py", line 93, in _write
    return super(Base, self)._write(vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3190, in _write
    cr.execute(query, params + (sub_ids,))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
ValueError: <class 'psycopg2.IntegrityError'>: "duplicate key value violates unique constraint "project_project_project_key_unique"
DETAIL:  Key (key)=(IP) already exists.
" while evaluating
'records.button_immediate_install()'

**Comment by grivalta** [comment]
Hi, in my case the same error appears if there was some addons already installed (Project, CRM, ecc.). If you start with a fresh install of Odoo 11 CE (in the case tested here is a Bitnami stack), also with demo data, you have to install first of all the "Project Key" module without errors. Next, you can install others modules of your interest.

**Comment by bobtownsend** [comment]
Hi.  In my case I am trying to install this on a copy of my production server which has other modules currently installed.  I did not try to install Project Key first.  I guess I missed that part in process.  It gives me similar and same errors as above.  If you would like I can show you my error log for the installation.  Do you have any recommendations for those of us which are already running other modules?  Thanks, Bob

**Comment by grivalta** [comment]
Hi @bobtownsend sorry but the only thing I have discovered is that metioned in my prev post. Until now I have not had the opportunity to further investigate the issue. I think, however, it may be useful to show your error log, maybe some other user can help on this... Best regards.

**Comment by raistdev** [comment]
Same issue. Don't work if Project is installed or it was installed.
