### ISSUE TITLE
Web_timeline : Uncaught TypeError: Cannot read property 'default_group_by' of undefined

### ISSUE THREAD

**Issue by nrdroque** [OCA/project#552]
opening the web_timeline get this error

Erro:
Uncaught TypeError: Cannot read property 'default_group_by' of undefined

http://crm.klc.pt:8069/web/content/1176-06a37c0/web.assets_backend.js:3142
Traceabilidade:
TypeError: Cannot read property 'default_group_by' of undefined
    at Class.init (http://crm.klc.pt:8069/web/content/1176-06a37c0/web.assets_backend.js:3142:751)
    at Class.prototype.(anonymous function) [as init] (http://crm.klc.pt:8069/web/content/807-87c3ed8/web.assets_common.js:3538:488)
    at new Class (http://crm.klc.pt:8069/web/content/807-87c3ed8/web.assets_common.js:3539:65)
    at Class._createViewController (http://crm.klc.pt:8069/web/content/1176-06a37c0/web.assets_backend.js:496:553)
    at newController (http://crm.klc.pt:8069/web/content/1176-06a37c0/web.assets_backend.js:510:155)
    at Class._switchController (http://crm.klc.pt:8069/web/content/1176-06a37c0/web.assets_backend.js:511:163)
    at Class._onSwitchView (http://crm.klc.pt:8069/web/content/1176-06a37c0/web.assets_backend.js:520:6)
    at Class.<anonymous> (http://crm.klc.pt:8069/web/content/807-87c3ed8/web.assets_common.js:3642:11)
    at Class.trigger (http://crm.klc.pt:8069/web/content/807-87c3ed8/web.assets_common.js:3640:180)
    at Class._trigger_up (http://crm.klc.pt:8069/web/content/807-87c3ed8/web.assets_common.js:3646:378)

**Comment by pedrobaeza** [comment]
Module itself doesn't do anything without a view showing it, so this should be at least applied on something, but any way, this seems an incorrect installation/deployment/update, so I'm closing this unless you prove real steps for replicating the problem.
