### ISSUE TITLE
[12.0][BUG] project_hr: Error when trying to create a new task from kanban view

### ISSUE THREAD

**Issue by gaikaz** [OCA/project#574]
module: `project_hr`
version: 12.0

In kanban view of tasks, creating a new task and trying to select the assigned user throws an error, saying `name 'allowed_user_ids' is not defined`.

![image](https://user-images.githubusercontent.com/17097810/64095599-ee02d780-cd67-11e9-84a9-707e303e7579.png)

Full error:
```
Uncaught Error: NameError: name 'allowed_user_ids' is not defined
http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/py.js/lib/py.js:369
Traceback:
Error: NameError: name 'allowed_user_ids' is not defined
    at PY_ensurepy (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/py.js/lib/py.js:369:19)
    at Object.py.evaluate (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/py.js/lib/py.js:1345:20)
    at Object.py.evaluate (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/py.js/lib/py.js:1402:38)
    at Object.py.evaluate (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/py.js/lib/py.js:1414:37)
    at Object.py.eval (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/py.js/lib/py.js:1458:19)
    at http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/src/js/core/py_utils.js:152:42
    at Function._.each._.forEach (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/underscore/underscore.js:145:9)
    at _.<computed> [as each] (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/lib/underscore/underscore.js:1484:34)
    at eval_domains (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/src/js/core/py_utils.js:143:16)
    at Object.pyeval [as eval] (http://3384492-12-0-0ac0b0.runbot1.odoo-community.org/web/static/src/js/core/py_utils.js:284:16)
```

**Steps to reproduce**
1. Open any project tasks in **Kanban view**
2. Start creating a **new task** in any column
3. Click on **Assigned to** selection field

**Current behavior**
Throws an error.

**Expected behavior**
Allows selecting the assigned user for the new task.

**Comment by gaikaz** [comment]
Something has changed. I cannot reproduce the error anymore.
It must have been this PR: https://github.com/OCA/project/pull/573
@alexey-pelykh , could this be the case?

Now clicking **Assigned to** just gives `No results to show...` as a selection, even though after creating the task, you can assign someone else.

![image](https://user-images.githubusercontent.com/17097810/64432636-95b03a80-d0c5-11e9-9a67-313a56a6a7f3.png)

Should this issue be considered solved?

**Comment by alexey-pelykh** [comment]
@gaikaz yes, that would've been affected by #573 yet your wording seems to reference another bug: if "assigned to" shows nothing initially, it should be nothing even after creation. @pedrobaeza did I get it right?

**Comment by pedrobaeza** [comment]
Well, if I don't remember bad, by default all users are allowed unless you restrict at project level.

**Comment by bodedra** [comment]
It seems we can close this issue.
