### ISSUE TITLE
Project timeline view error in Android mobile chrome

### ISSUE THREAD

**Issue by julius3419** [OCA/project#633]
module: project_timeline
version: 12.0
As soon as i switched to the "timeline" view in project or task, in the android chrome browser, the error below appeared.

Error:
Uncaught TypeError: Cannot read property 'icon' of undefined

http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1293
Traceback:
TypeError: Cannot read property 'icon' of undefined
    at Class._renderSwitchButtons (http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1293:695)
    at Class._renderControlPanelElements (http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1291:390)
    at Class.start (http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1283:1427)
    at Class.prototype.<computed> [as start] (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:3538:488)
    at http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:3684:52
    at http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:802:649)
    at Function.each (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:625:767)

- ...

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Closing as it's the same as https://github.com/OCA/web/issues/1488
