### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by carlosecv** [OCA/project#682]
Trying to install project_key module to my existing database with some projects and tasks allredy recorded we get this error

Odoo Version: 11.0

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-38>", line 2, in button_immediate_install
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 200, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/opt/odoo/auto/addons/project_key/hooks.py", line 8, in post_init_hook
    env['project.project']._set_default_project_key()
  File "/opt/odoo/auto/addons/project_key/models/project_project.py", line 180, in _set_default_project_key
    project.key = self.generate_project_key(project.name)
  File "/opt/odoo/auto/addons/project_key/models/project_project.py", line 143, in generate_project_key
    key.append(item[0].upper())
IndexError: string index out of range

**Comment by skeller1** [comment]
Hi, there seems to be an project with an empty name (or with one or more spaces). Maybe an empty project name is a possible scenario in some companies. So maybe we should strip the text before.
Could you check this please?

**Comment by skeller1** [comment]
Hi, there seems to be an project with an empty name (or with one or more spaces). Maybe an empty project name is a possible scenario in some companies. So maybe we should strip the text before.
Could you check this please?
