### ISSUE TITLE
 Error while importing module 'project_template'.

### ISSUE THREAD

**Issue by JurajRech** [OCA/project#902]
when trying to import poject_template in v14 enterprise odoo, I get an error:

 Error while importing module 'project_template'.

```
_while parsing /tmp/tmpy9_y01xc/project_template/views/project.xml:3, near
<record id="project_template_view_inherit_form" model="ir.ui.view">
        <field name="name">project.template.form</field>
        <field name="model">project.project</field>
        <field name="inherit_id" ref="project.edit_project"/>
        <field name="type">form</field>
        <field name="arch" type="xml">
            <data><xpath expr="//header" position="inside">
                <button string="Create Project From Template" type="object" name="create_project_from_template" class="oe_highlight" attrs="{'invisible': [('is_template', '=', False)]}"/>
            </xpath>
            <xpath expr="//div[@name='options_active']" position="inside">
                <div>
                    <field name="is_template" class="oe_inline" string="Is Template?"/>
                    <label for="is_template"/>
                </div>
            </xpath>
        </data></field>
    </record> 
 Make sure those modules are installed and try again._
```

**Comment by JurajRech** [comment]
after sucessful installation of the addon I am getting an error when trying to create any new project

`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6211, in onchange
    record = self.new(initial_values, origin=self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5515, in new
    record._update_cache(values, validate=False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5157, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'is_template' on model 'project.project'`

**Comment by pedrobaeza** [comment]
You mustn't import modules. That's only for data modules (like themes). You have to add it to your addons path properly.
